openapi: 3.0.0
info:
  title: Hapus Data Course
  version: 1.0.0
tags:
  - name: Daftar API
parameters:
  - name: course_id
    in: path
    description: ID Course yang akan dihapus
    required: true
    type: integer
responses:
  200:
    description: Data course berhasil dihapus
  404:
    description: Data tidak ditemukan
