openapi: 3.0.0
info:
  title: Hapus Data Enrollment
  version: 1.0.0
tags:
  - name: Daftar API
parameters:
  - name: enrollment_id
    in: path
    description: ID Enrollment yang akan dihapus
    required: true
    type: integer
responses:
  200:
    description: Data enrollment berhasil dihapus
  404:
    description: Data tidak ditemukan
