openapi: 3.0.0
info:
  title: Update Data course
  version: 1.0.0
tags:
  - name: Daftar API
parameters:
  - name: course_id
    in: path
    descriptions: ID course yang akan diambil
    required: true
    type: integer
  - in: body
    name: body
    description: Data course yang akan diperbarui
    required: true
    schema:
      $ref: '#/definitions/Courses'
responses:
  200:
    description: Data berhasil diperbarui
    schema:
      $ref: '#/definitions/Courses'
  400:
    description: Data tidak ditemukan